[theme]
primaryColor = "#d8a5e3"
backgroundColor = "#faf5ff"
secondaryBackgroundColor = "#ffe6f5"
textColor = "#2c3e50"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[server]
headless = true
port = 8501
enableXsrfProtection = true
enableCORS = false
